var folio = require('folio');

folio('chai')
  .loglevel('info')
  .root(__dirname, '..')
  .out('./')
  .min(false)
  .strategy(folio.requires())
    .package('chai')
    .dir('./lib')
    .entry('./chai.js')
    .ignore('./chai/error.js')
    .replace('./chai/error', './chai/browser/error')
    .replace('./error', './browser/error')
    .pop()
  .strategy(folio.wrapper())
    .template('amd')
    .expose("require('chai')")
    .pop()
  .compile();
