var folio = require('folio');

folio('chai')
  .root(__dirname, '..')
  .use(folio.requires())
    .dir('./lib')
    .package('chai')
    .entry('./chai.js')
    .ignore('./chai/error.js')
    .replace('./chai/error', './chai/browser/error')
    .replace('./error', './browser/error')
    .pop()
  .use(folio.indent())
    .line('  ')
    .pop()
  .use(folio.wrapper())
    .template('amd')
    .package('chai')
    .expose("require('chai')")
    .pop()
  .use(folio.save())
    .file('./chai.js')
    .pop()
  .compile();
